spring:
  application:
    name: chat

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

chat:
  cors:
    allowed-origin-patterns:
      - http://localhost:*
      - http://127.0.0.1:*
  files:
    max-size: 10485760 # 10 MB
    storage-path: ./storage/chat

server:
  port: 8080
